# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
from os.path import dirname, relpath
import inspect
import sphinx
from setuptools_scm import get_version

sys.path.insert(0, os.path.abspath(".."))

import autoreduce


# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "autoreduce"
copyright = "2026, Ayush Pandey"
author = "Ayush Pandey"

release = get_version(root="..", relative_to=__file__)
version = ".".join(release.split(".", 2)[:2])


# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.linkcode",
    "sphinx.ext.mathjax",
    "sphinx.ext.napoleon",
    "sphinx_copybutton",
    "sphinx_toggleprompt",
    "sphinx_math_dollar",
    "nbsphinx",
    "nbsphinx_link",
    "recommonmark",
    "numpydoc",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {".rst": "restructuredtext"}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "_autogen_*.rst", "Thumbs.db", ".DS_Store"]
suppress_warnings = ["config.cache"]

autosummary_generate = True
autodoc_default_options = {
    "exclude-members": "__init__, __weakref__, __repr__, __str__, __hash__",
}
autoclass_content = "class"
autodoc_mock_imports = ["control", "pydmd"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"
default_role = "py:obj"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["css/custom.css"]

sphinx_version = tuple(int(x) for x in sphinx.__version__.split(".")[:2])
if sphinx_version >= (4, 0):
    mathjax3_config = {
        "tex": {
            "inlineMath": [["\\(", "\\)"]],
            "displayMath": [["\\[", "\\]"]],
        }
    }
else:
    mathjax_config = {
        "tex2jax": {
            "inlineMath": [["\\(", "\\)"]],
            "displayMath": [["\\[", "\\]"]],
        },
    }

copybutton_prompt_text = r">>> |\.\.\. "
copybutton_prompt_is_regexp = True
numpydoc_show_class_members = False
numpydoc_class_members_toctree = False
nbsphinx_execute = "never"

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "AutoReduce"


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, "autoreduce", "AutoReduce Documentation", [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "AutoReduce",
        "AutoReduce Documentation",
        author,
        "AutoReduce",
        "One line description of project.",
        "Miscellaneous",
    ),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ["search.html"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "sympy": ("https://docs.sympy.org/latest/", None),
}
intersphinx_disabled_reftypes = ["py:keyword"]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = True
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

autodoc_member_order = "bysource"
autodoc_typehints = "description"
add_module_names = False


def linkcode_resolve(domain, info):
    """Resolve documented Python objects to GitHub source links."""
    if domain != "py":
        return None

    module_name = info["module"]
    full_name = info["fullname"]
    module = sys.modules.get(module_name)
    if module is None:
        return None

    obj = module
    for part in full_name.split("."):
        try:
            obj = getattr(obj, part)
        except AttributeError:
            return None

    obj = inspect.unwrap(obj)
    try:
        source_file = inspect.getsourcefile(obj)
        source, line_number = inspect.getsourcelines(obj)
    except (OSError, TypeError):
        return None
    if not source_file:
        return None

    source_module = inspect.getmodule(obj)
    if source_module is not None and not source_module.__name__.startswith(
        "autoreduce"
    ):
        return None

    relative_file = relpath(source_file, start=dirname(autoreduce.__file__))
    line_spec = f"#L{line_number}-L{line_number + len(source) - 1}"
    if release != version:
        return (
            "https://github.com/ayush9pandey/AutoReduce/blob/"
            f"main/autoreduce/{relative_file}{line_spec}"
        )
    return (
        "https://github.com/ayush9pandey/AutoReduce/blob/"
        f"v{version}/autoreduce/{relative_file}{line_spec}"
    )


doctest_global_setup = """
import numpy as np
import autoreduce
"""
